[versions]
agp_version = "8.2.1"
coroutines_version = "1.7.1"
kotlin_version = "2.1.0"
serialization_version = "1.8.0"
dokkatoo_version = "2.1.0"
binary_compat_validator_version = "0.17.0"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }

kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_version" }
kotlin-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization_version" }

injekt-core = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
jsoup = { module = "org.jsoup:jsoup", version = "1.18.3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.14" }
rxandroid = { module = "io.reactivex:rxandroid", version = "1.2.1" }
rxjava = { module = "io.reactivex:rxjava", version = "1.3.8" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp_version" }
dokkatoo = { id = "dev.adamko.dokkatoo", version.ref = "dokkatoo_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary_compat_validator_version" }
